# yaml 配置
version: "3.7"
services:
  mysqllatest:
  # shortener:
    image: "mysql:latest"
    ports:
      - "9306:3306"
    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "root1234"
      MYSQL_DATABASE: "shortener"
      MYSQL_PASSWORD: "root1234"
    volumes:
      - ./model/sql/init.sql:/data/application/init.sql
  
  redis507:
    image: "redis:5.0.7"
    ports:
      - "9379:6379"
  # bubble_app:
  #   build: .
  #   command: sh -c "./wait-for.sh mysql8019:3306 -- ./bubble ./conf/config.yaml"
  #   depends_on:
  #     - mysql8019
  #   ports:
  #     - "8888:8888"
